### ISSUE TITLE
Create Job

### ISSUE THREAD

**Issue by Olayiwola72** [den1n/nova-queues#4]
Please, how can we hide or disable the create job button

![image](https://user-images.githubusercontent.com/40915435/133451108-0390e9f1-cb6c-4a42-bd46-35836f8a0fc1.png)

**Comment by den1n** [comment]
You can use policy. 
https://nova.laravel.com/docs/3.0/resources/authorization.html

Or override some methods in Job resource.
https://github.com/laravel/nova-issues/issues/2593

**Comment by Olayiwola72** [comment]
I have used policy for a couple of resources, in this case, I do not know how to create policy for this tool, do I run "php artisan make:policy JobPolicy --model=Jobs" or something?

**Comment by den1n** [comment]
Instead of modifying source of the package you can override whole Job resource.

Please follow these steps:

1. Create your own App\Nova\Job resource.

```
namespace App\Nova;

class Job extends \Den1n\NovaQueues\Resources\Job
{
    public static function authorizedToCreate(Request $request)
    {
        return false;
    }
}
```

2. Set your new Job resource in config/nova-queues.php file.

```
'resources' => [
    'job' => \App\Nova\Job::class,
    'failed_job' => \Den1n\NovaQueues\Resources\FailedJob::class,
],
```

Please let me know if it works.

**Comment by Olayiwola72** [comment]
Thank you so much @den1n . This works perfectly
