### ISSUE TITLE
Supported queue drivers

### ISSUE THREAD

**Issue by clementmas** [den1n/nova-queues#5]
Does this package only work with the database queue driver?

I'm guessing yes but it's unclear. I think the readme should mention that clearly.

Thanks!

**Comment by den1n** [comment]
Yes, this package only works with the database driver because Laravel Nova does not support Redis.

I have added a note about the supported driver in the readme.

You can use [Laravel Horizon](https://laravel.com/docs/9.x/horizon) if you are using the Redis queue driver.
